### ISSUE TITLE
cv_BUG

### ISSUE THREAD

**Issue by cfz1998** [joy50706/iAMPCN#3]
https://github.com/joy50706/iAMPCN/blob/master/predict.py#L145-150

**Comment by cfz1998** [comment]
what's the means about `textcnn_cdhit_100_0.pth.tar`?

**Comment by cfz1998** [comment]
Maybe `textcnn_cdhit_100_{cv_number}.pth.tar`?

**Comment by xinyimou** [comment]
I have found the same problem. It may be a mistake by the authors.

It should be changed into
'''
        for cv_number in range(10):
            testing(testfasta=fas_seq,
                    model_file=f'models/AMP_2nd/{function_name}/textcnn_cdhit_100_{cv_number}.pth.tar',
                    save_file=f'tmp_save/{function_name}/{temp_save_AMP_filename}_{cv_number}.csv',
                    batch_size=batch_size, patience=10, n_epochs=epochs,seq_len=seq_len,cdhit_value=cdhit_value,cv_number=cv_number)
'''
as you mentioned.
Otherwise, the input data will only be predicted by the first model of the ten folds, and get the same probabilities.
